services:
  
  # Template + Student 1
  app1:
    #build: .
    image: "cdipc/app-prebuilt:latest"
    tty: true
    hostname: cdipcapp
    entrypoint: ["/apps/infa/scripts/prebuilt.sh"]
    depends_on:
      db1:
        condition: service_started
        restart: true
    ports:
      - 9441:8443
      - 221:22
    networks:
      - net1

  db1:
    image: "postgres:14.3-alpine"
    restart: always
    shm_size: 128mb
    hostname: cdipcdb
    environment:
      POSTGRES_USER: infa
      POSTGRES_PASSWORD: infa
      POSTGRES_DB: infa
    volumes:
      - ./database/prebuilt.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 7431:5432
    networks:
      - net1

# Network definitions
networks:
  net1:
